// Checks ImuPreintegrator against ground truth generated by integrating the kinematics directly.
//
// The reference motion is a constant body-frame turn rate with a constant body-frame acceleration,
// sampled noise-free, so every quantity below has a closed reference to compare against.

#include <gtest/gtest.h>

#include <Eigen/Geometry>
#include <vector>

#include "imu_preint/imu_preintegrator.hpp"
#include "imu_preint/so3.hpp"

namespace
{
using imu_preint::ImuPreintegrator;
using imu_preint::NavState;
using imu_preint::PreintegratedDelta;
namespace so3 = imu_preint::so3;

/// One noise-free IMU sample.
struct Sample
{
    Eigen::Vector3d gyro = Eigen::Vector3d::Zero();
    Eigen::Vector3d accel = Eigen::Vector3d::Zero();
};

/// Ground-truth motion: a constant turn rate with a constant body acceleration.
struct GroundTruthMotion
{
    Eigen::Vector3d gravity = Eigen::Vector3d(0.0, 0.0, -9.80665);
    Eigen::Vector3d body_rate = Eigen::Vector3d(0.02, -0.03, 0.15);  ///< [rad/s]
    Eigen::Vector3d body_accel = Eigen::Vector3d(0.4, 0.15, -0.05);  ///< [m/s^2], body frame

    /// Builds the true state by integrating the kinematics directly, emitting the samples it implies.
    NavState Integrate(NavState state, double dt, int steps, std::vector<Sample>* samples) const
    {
        for (int k = 0; k < steps; ++k)
        {
            if (samples != nullptr)
            {
                Sample sample;
                sample.gyro = body_rate;
                // The accelerometer measures the specific force f = R^T (a_world - g).
                sample.accel = body_accel - state.rotation.transpose() * gravity;
                samples->push_back(sample);
            }
            const Eigen::Vector3d accel_world = state.rotation * body_accel;
            state.position += state.velocity * dt + 0.5 * accel_world * dt * dt;
            state.velocity += accel_world * dt;
            state.rotation = state.rotation * so3::Exp(body_rate * dt);
            state.timestamp += dt;
        }
        return state;
    }
};

/// The state the reference motion starts from, deliberately not the identity.
NavState MakeInitialState()
{
    NavState state;
    state.rotation = Eigen::AngleAxisd(0.3, Eigen::Vector3d(0.2, -0.5, 0.84).normalized()).toRotationMatrix();
    state.velocity = Eigen::Vector3d(3.0, -1.0, 0.2);
    state.position = Eigen::Vector3d(10.0, -5.0, 1.0);
    return state;
}

constexpr double kDt = 0.005;
constexpr int kSteps = 200;  // 1.0 s

/// Integrates the first @p steps samples into a fresh preintegrator.
ImuPreintegrator Preintegrate(const std::vector<Sample>& samples, int steps)
{
    ImuPreintegrator preintegrator;
    for (int k = 0; k < steps; ++k)
    {
        preintegrator.integrate(samples[k].gyro, samples[k].accel, kDt);
    }
    return preintegrator;
}

/// Fixture holding one reference run: the true end state plus the samples that produce it.
class Preintegration : public ::testing::Test
{
protected:
    void SetUp() override
    {
        state_i_ = MakeInitialState();
        state_j_ = motion_.Integrate(state_i_, kDt, kSteps, &samples_);
    }

    GroundTruthMotion motion_;
    NavState state_i_;
    NavState state_j_;
    std::vector<Sample> samples_;
};

TEST_F(Preintegration, ResetLeavesTheIdentityDelta)
{
    ImuPreintegrator preintegrator = Preintegrate(samples_, kSteps);
    ASSERT_EQ(preintegrator.num_samples(), kSteps);

    preintegrator.reset();
    const PreintegratedDelta delta = preintegrator.delta();

    EXPECT_EQ(preintegrator.num_samples(), 0);
    EXPECT_DOUBLE_EQ(preintegrator.delta_t(), 0.0);
    EXPECT_DOUBLE_EQ(delta.dt, 0.0);
    EXPECT_LT((delta.rotation - Eigen::Matrix3d::Identity()).norm(), 1e-15);
    EXPECT_LT(delta.velocity.norm(), 1e-15);
    EXPECT_LT(delta.position.norm(), 1e-15);
}

TEST_F(Preintegration, NonPositiveDtIsIgnored)
{
    ImuPreintegrator preintegrator;
    preintegrator.integrate(samples_[0].gyro, samples_[0].accel, 0.0);
    preintegrator.integrate(samples_[0].gyro, samples_[0].accel, -kDt);

    EXPECT_EQ(preintegrator.num_samples(), 0);
    EXPECT_DOUBLE_EQ(preintegrator.delta_t(), 0.0);
}

TEST_F(Preintegration, DeltasMatchTheirDefinitions)
{
    const ImuPreintegrator preintegrator = Preintegrate(samples_, kSteps);
    const PreintegratedDelta delta = preintegrator.delta();
    const double dt_ij = delta.dt;

    EXPECT_NEAR(dt_ij, kSteps * kDt, 1e-12);

    // The definitions the recursion is supposed to reproduce:
    //   dR_ij = R_i^T R_j,  dv_ij = R_i^T(v_j - v_i - g dt),
    //   dp_ij = R_i^T(p_j - p_i - v_i dt - 0.5 g dt^2)
    const Eigen::Matrix3d Ri_transpose = state_i_.rotation.transpose();
    const Eigen::Matrix3d expected_rotation = Ri_transpose * state_j_.rotation;
    const Eigen::Vector3d expected_velocity = Ri_transpose * (state_j_.velocity - state_i_.velocity - motion_.gravity * dt_ij);
    const Eigen::Vector3d expected_position =
            Ri_transpose * (state_j_.position - state_i_.position - state_i_.velocity * dt_ij - 0.5 * motion_.gravity * dt_ij * dt_ij);

    EXPECT_NEAR(so3::Log(delta.rotation.transpose() * expected_rotation).norm(), 0.0, 1e-9);
    EXPECT_NEAR((delta.velocity - expected_velocity).norm(), 0.0, 1e-9);
    EXPECT_NEAR((delta.position - expected_position).norm(), 0.0, 1e-9);
}

TEST_F(Preintegration, PredictReproducesTheTrueState)
{
    const ImuPreintegrator preintegrator = Preintegrate(samples_, kSteps);
    const NavState predicted = preintegrator.predict(state_i_, motion_.gravity);

    EXPECT_NEAR(predicted.timestamp, state_j_.timestamp, 1e-12);
    EXPECT_NEAR((predicted.position - state_j_.position).norm(), 0.0, 1e-9);
    EXPECT_NEAR((predicted.velocity - state_j_.velocity).norm(), 0.0, 1e-9);
    EXPECT_NEAR(so3::Log(predicted.rotation.transpose() * state_j_.rotation).norm(), 0.0, 1e-9);
}

TEST_F(Preintegration, DeltaIsIndependentOfTheAbsoluteState)
{
    // The whole point of preintegration: the delta holds no absolute state and no gravity, so an
    // entirely different state i must still satisfy the delta definitions without re-integrating.
    const ImuPreintegrator preintegrator = Preintegrate(samples_, kSteps);
    const PreintegratedDelta delta = preintegrator.delta();
    const double dt_ij = delta.dt;

    NavState other;
    other.rotation = Eigen::AngleAxisd(-1.1, Eigen::Vector3d(0.6, 0.3, -0.74).normalized()).toRotationMatrix();
    other.velocity = Eigen::Vector3d(-7.0, 2.5, 0.9);
    other.position = Eigen::Vector3d(-40.0, 12.0, -3.0);

    const NavState other_j = preintegrator.predict(other, motion_.gravity);
    const Eigen::Matrix3d R_transpose = other.rotation.transpose();

    EXPECT_NEAR(so3::Log(delta.rotation.transpose() * (R_transpose * other_j.rotation)).norm(), 0.0, 1e-9);
    EXPECT_NEAR((delta.velocity - R_transpose * (other_j.velocity - other.velocity - motion_.gravity * dt_ij)).norm(), 0.0, 1e-9);
    EXPECT_NEAR(
            (delta.position - R_transpose * (other_j.position - other.position - other.velocity * dt_ij - 0.5 * motion_.gravity * dt_ij * dt_ij)).norm(),
            0.0, 1e-9);
}

TEST_F(Preintegration, RotationStaysOrthonormal)
{
    const ImuPreintegrator preintegrator = Preintegrate(samples_, kSteps);
    const Eigen::Matrix3d rotation = preintegrator.delta().rotation;

    EXPECT_LT((rotation.transpose() * rotation - Eigen::Matrix3d::Identity()).norm(), 1e-12);
    EXPECT_NEAR(rotation.determinant(), 1.0, 1e-12);
}

TEST_F(Preintegration, DeltaAtMatchesAnIntegrationUpToThatTime)
{
    // delta_at() is what deskewing queries per point, at the point's own capture time.
    const ImuPreintegrator preintegrator = Preintegrate(samples_, kSteps);

    const int half_steps = kSteps / 2;
    const PreintegratedDelta half = preintegrator.delta_at(half_steps * kDt);
    const PreintegratedDelta reference = Preintegrate(samples_, half_steps).delta();

    EXPECT_NEAR(so3::Log(half.rotation.transpose() * reference.rotation).norm(), 0.0, 1e-9);
    EXPECT_NEAR((half.velocity - reference.velocity).norm(), 0.0, 1e-9);
    EXPECT_NEAR((half.position - reference.position).norm(), 0.0, 1e-9);
}

TEST_F(Preintegration, DeltaAtClampsOutsideTheInterval)
{
    const ImuPreintegrator preintegrator = Preintegrate(samples_, kSteps);
    const PreintegratedDelta full = preintegrator.delta();

    const PreintegratedDelta before = preintegrator.delta_at(-1.0);
    EXPECT_DOUBLE_EQ(before.dt, 0.0);
    EXPECT_LT((before.rotation - Eigen::Matrix3d::Identity()).norm(), 1e-15);
    EXPECT_LT(before.position.norm(), 1e-15);

    const PreintegratedDelta after = preintegrator.delta_at(full.dt + 1.0);
    EXPECT_DOUBLE_EQ(after.dt, full.dt);
    EXPECT_LT((after.position - full.position).norm(), 1e-15);
}

TEST(PreintegrationEdgeCases, DeltaAtOnAnEmptyIntervalIsTheIdentity)
{
    const ImuPreintegrator preintegrator;
    const PreintegratedDelta delta = preintegrator.delta_at(0.5);

    EXPECT_DOUBLE_EQ(delta.dt, 0.0);
    EXPECT_LT((delta.rotation - Eigen::Matrix3d::Identity()).norm(), 1e-15);
    EXPECT_LT(delta.velocity.norm(), 1e-15);
    EXPECT_LT(delta.position.norm(), 1e-15);
}

TEST(PreintegrationEdgeCases, ZeroMotionPredictsFreeFall)
{
    // No rotation and no specific force: the body is in free fall, so predict() must return exactly
    // the ballistic solution p_j = p_i + v_i t + 0.5 g t^2.
    const Eigen::Vector3d gravity(0.0, 0.0, -9.80665);
    ImuPreintegrator preintegrator;
    for (int k = 0; k < kSteps; ++k)
    {
        preintegrator.integrate(Eigen::Vector3d::Zero(), Eigen::Vector3d::Zero(), kDt);
    }

    NavState state_i;
    state_i.velocity = Eigen::Vector3d(1.0, 2.0, 3.0);
    const NavState predicted = preintegrator.predict(state_i, gravity);

    const double t = kSteps * kDt;
    EXPECT_NEAR((predicted.velocity - (state_i.velocity + gravity * t)).norm(), 0.0, 1e-12);
    EXPECT_NEAR((predicted.position - (state_i.velocity * t + 0.5 * gravity * t * t)).norm(), 0.0, 1e-12);
    EXPECT_LT((predicted.rotation - Eigen::Matrix3d::Identity()).norm(), 1e-15);
}

}  // namespace
